In [21]:
import numpy as np
import pandas as pd

In [22]:
#cgpa = pd.DataFrame(columns=["Subject" , "Course_Type" , "Grade" , "Credit"])

In [23]:
cgpa = pd.read_csv("cgpa.csv")

In [24]:
cgpa

                  Subject Course_Type  Grade  Credit
0            LABORATORY I        Core     A-       4
1             ELECTRONICS        Core     A-       4
2    MATHEMATICAL PHYSICS        Core     A-       4
3     CLASSICAL MECHANICS        Core      B       4
4     QUANTUM MECHANICS I        Core     A-       4
5                   CTSSM          PE      B       3
6         Electrodynamics        Core      B       4
7     Solid State Physics        Core      B       4
8           Laboratory II        Core      B       4
9          Applied Optics        Core     B-       4
10   Quantum Mechanics II        Core     B-       3
11           Group Theory          PE  Audit       3
12  Statistical Mechanics        Core  Audit       4

In [25]:
grading_system = {"A":10, "A-":9, "B":8, "B-":7, "C":6, "C-":5, "D":4, "D-":3, "E":2, "F":1, "F-":0}

In [26]:
cgpa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Subject      13 non-null     object
 1   Course_Type  13 non-null     object
 2   Grade        13 non-null     object
 3   Credit       13 non-null     int64
dtypes: int64(1), object(3)
memory usage: 544.0+ bytes

In [27]:
cgpa

                  Subject Course_Type  Grade  Credit
0            LABORATORY I        Core     A-       4
1             ELECTRONICS        Core     A-       4
2    MATHEMATICAL PHYSICS        Core     A-       4
3     CLASSICAL MECHANICS        Core      B       4
4     QUANTUM MECHANICS I        Core     A-       4
5                   CTSSM          PE      B       3
6         Electrodynamics        Core      B       4
7     Solid State Physics        Core      B       4
8           Laboratory II        Core      B       4
9          Applied Optics        Core     B-       4
10   Quantum Mechanics II        Core     B-       3
11           Group Theory          PE  Audit       3
12  Statistical Mechanics        Core  Audit       4

In [28]:
while(input("Want to enter data") == "yes"):
    subject = input("Enter subject")
    course_type = input("Enter course type")
    grade = input("Enter grade")
    credit = int(input("Enter credit"))
    cgpa.loc[len(cgpa)] = [subject, course_type, grade, credit]

In [29]:
cgpa

                  Subject Course_Type  Grade  Credit
0            LABORATORY I        Core     A-       4
1             ELECTRONICS        Core     A-       4
2    MATHEMATICAL PHYSICS        Core     A-       4
3     CLASSICAL MECHANICS        Core      B       4
4     QUANTUM MECHANICS I        Core     A-       4
5                   CTSSM          PE      B       3
6         Electrodynamics        Core      B       4
7     Solid State Physics        Core      B       4
8           Laboratory II        Core      B       4
9          Applied Optics        Core     B-       4
10   Quantum Mechanics II        Core     B-       3
11           Group Theory          PE  Audit       3
12  Statistical Mechanics        Core  Audit       4

In [30]:
sem_1 = cgpa.iloc[:5,:]
sem_2 = cgpa.iloc[5:,:]

In [31]:
print("Semester-1\n\n",sem_1,"\n\nSemester-2\n\n",sem_2)

Semester-1

                 Subject Course_Type Grade  Credit
0          LABORATORY I        Core    A-       4
1           ELECTRONICS        Core    A-       4
2  MATHEMATICAL PHYSICS        Core    A-       4
3   CLASSICAL MECHANICS        Core     B       4
4   QUANTUM MECHANICS I        Core    A-       4

Semester-2

                   Subject Course_Type  Grade  Credit
5                   CTSSM          PE      B       3
6         Electrodynamics        Core      B       4
7     Solid State Physics        Core      B       4
8           Laboratory II        Core      B       4
9          Applied Optics        Core     B-       4
10   Quantum Mechanics II        Core     B-       3
11           Group Theory          PE  Audit       3
12  Statistical Mechanics        Core  Audit       4

In [32]:
def calculate_cgpa(cgpa):
    total_credit = 0
    total_grade = 0
    for i in range(len(cgpa)):
        if cgpa.iloc[i][2] != "Audit":
            total_credit += cgpa.iloc[i][3]
            total_grade += cgpa.iloc[i][3] * grading_system[cgpa.iloc[i][2]]
    return total_grade/total_credit

In [33]:
print("Semester-1: ",calculate_cgpa(sem_1))
print("Semester-2: ",calculate_cgpa(sem_2))
print("Total:      ",calculate_cgpa(cgpa))

Semester-1:  8.8
Semester-2:  7.681818181818182
Total:       8.214285714285714

In [34]:
cgpa.to_csv("cgpa.csv", index=False)